[platformio]
src_dir = examples/BrowserAudio

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
lib_deps = ESP32-Arduino-WebRTC=symlink://.
build_flags = -DCORE_DEBUG_LEVEL=1

[env:esp32s3]
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_qspi
board_build.partitions = huge_app.csv

[env:esp32]
board = esp32dev
board_build.partitions = huge_app.csv

[env:esp32s3_16k]
extends = env:esp32s3
build_flags = ${env.build_flags} -DWEBRTC_SAMPLE_RATE=16000

[env:esp32s3_48k]
extends = env:esp32s3
build_flags = ${env.build_flags} -DWEBRTC_SAMPLE_RATE=48000

[env:esp32s3_g711]
extends = env:esp32s3
build_flags = ${env.build_flags} -DWEBRTC_SAMPLE_RATE=8000 -DWEBRTC_USE_G711=1
